// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGS_eLwsK-oW9PjEdWS1OBTqjj8iNTqbk',
    appId: '1:1077024338986:web:3296df2e1fe58da4e53f53',
    messagingSenderId: '1077024338986',
    projectId: 'my-project-fc998',
    authDomain: 'my-project-fc998.firebaseapp.com',
    storageBucket: 'my-project-fc998.firebasestorage.app',
    measurementId: 'G-F2738L1XC7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAykhZmbVE-ZW3UCO0VQHgVVKLEUqomvMc',
    appId: '1:1077024338986:android:434f7e396d90078de53f53',
    messagingSenderId: '1077024338986',
    projectId: 'my-project-fc998',
    storageBucket: 'my-project-fc998.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVEmtUOWBgFRzkjEsIVKzVqsOL1B8lY-M',
    appId: '1:1077024338986:ios:9745b6e8f84fe9bde53f53',
    messagingSenderId: '1077024338986',
    projectId: 'my-project-fc998',
    storageBucket: 'my-project-fc998.firebasestorage.app',
    iosBundleId: 'com.example.myProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVEmtUOWBgFRzkjEsIVKzVqsOL1B8lY-M',
    appId: '1:1077024338986:ios:9745b6e8f84fe9bde53f53',
    messagingSenderId: '1077024338986',
    projectId: 'my-project-fc998',
    storageBucket: 'my-project-fc998.firebasestorage.app',
    iosBundleId: 'com.example.myProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGS_eLwsK-oW9PjEdWS1OBTqjj8iNTqbk',
    appId: '1:1077024338986:web:b118efb46a00b9a5e53f53',
    messagingSenderId: '1077024338986',
    projectId: 'my-project-fc998',
    authDomain: 'my-project-fc998.firebaseapp.com',
    storageBucket: 'my-project-fc998.firebasestorage.app',
    measurementId: 'G-YPYZ66G3LH',
  );
}
