// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-9OYMQL2gPgim27wDtfTN4SrjJCEniH4',
    appId: '1:652608054246:web:78bd68cdc9cf7690efac27',
    messagingSenderId: '652608054246',
    projectId: 'meraapp-84c69',
    authDomain: 'meraapp-84c69.firebaseapp.com',
    storageBucket: 'meraapp-84c69.firebasestorage.app',
    measurementId: 'G-QY6R2TSZB1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwsM7_KDv-_myR2WVZ05piV0-itq2ueow',
    appId: '1:652608054246:android:f2216d238f0a99b9efac27',
    messagingSenderId: '652608054246',
    projectId: 'meraapp-84c69',
    storageBucket: 'meraapp-84c69.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUgaprS3xd_V37tf9NkkaIp_66HK7xgyc',
    appId: '1:652608054246:ios:aac83382f32fd242efac27',
    messagingSenderId: '652608054246',
    projectId: 'meraapp-84c69',
    storageBucket: 'meraapp-84c69.firebasestorage.app',
    iosClientId: '652608054246-rv7s1schukuhk3f2mhfqdqu68c2ulcdr.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUgaprS3xd_V37tf9NkkaIp_66HK7xgyc',
    appId: '1:652608054246:ios:aac83382f32fd242efac27',
    messagingSenderId: '652608054246',
    projectId: 'meraapp-84c69',
    storageBucket: 'meraapp-84c69.firebasestorage.app',
    iosClientId: '652608054246-rv7s1schukuhk3f2mhfqdqu68c2ulcdr.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseApp',
  );
}
